tap "dart-lang/dart"
tap "derailed/k9s"
tap "jandedobbeleer/oh-my-posh"
tap "sass/sass"

brew "bat"
brew "cloud-provider-kind"
brew "cmake"
brew "derailed/k9s/k9s"
brew "dotnet"
brew "dust"
brew "gcc"
brew "gh"
brew "git"
brew "git-delta"
brew "go"
brew "grpcurl"
brew "helm"
brew "htop"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"
brew "jq"
brew "kind"
brew "kubernetes-cli"
brew "mas"
brew "maven"
brew "mole"
brew "neovim"
brew "ollama"
brew "pipx"
brew "pyenv"
brew "telnet"
brew "unp"
brew "uv"
brew "watch"
brew "wget"
brew "yq"
brew "zsh"
brew "sass/sass/sass"

cask "bruno"
cask "font-jetbrains-mono"
cask "font-meslo-lg-nerd-font"
cask "jetbrains-toolbox"
cask "kitty"

mas "Bitwarden", id: 1352778147
mas "Microsoft To Do", id: 1274495053
